# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='outside_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_joined', to='chat.Profile'),
        ),
    ]
