# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170415_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='pub_date',
            new_name='text',
        ),
    ]
