# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170415_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.CharField(default=b'Hello', max_length=500),
        ),
        migrations.AddField(
            model_name='topic',
            name='on_board',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
