# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
    ]
