# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_recieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unseen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unseen_messages', to='chat.Profile'),
        ),
    ]
