# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chat_unseen_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(default='blue', max_length=7),
            preserve_default=False,
        ),
    ]
